#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18052
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PresenterDailyShower.Resource", IsApplication=true)]

namespace PresenterDailyShower
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int grey = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int lightgrey = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int listseparator = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int red = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int white = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int yellow = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon_presents_72 = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int EmailLabel = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int FirstNameLabel = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int HospitalLabel = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int PositionLabel = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int PresentLabel = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int SecondNameLabel = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int SpecialityLabel = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int TelLabel = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int ThirdNameLabel = 2131099654;
			
			// aapt resource value: 0x7f06000e
			public const int btnShow = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int ivSlide = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int llBottom = 2131099667;
			
			// aapt resource value: 0x7f060002
			public const int llDetail = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int llList = 2131099648;
			
			// aapt resource value: 0x7f060010
			public const int llTop = 2131099664;
			
			// aapt resource value: 0x7f060001
			public const int lvList = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int scrDetail = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int spnPresents = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int txtHospital = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int txtView = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainListHeader = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PresentationView = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
